[package]
name = "opossum-file"
version = "0.1.0"
edition.workspace = true
repository.workspace = true
description = "Convert ScanCode JSON, Opossum files, and OWASP Dependency Scan JSON into .opossum format"
homepage = "https://github.com/opossum-tool/opossum-file.rs"

[package.metadata.dist]
dashed = false

[dependencies]
opossum-lib = { path = "../opossum-lib" }
clap = { version = "4.5", features = ["derive"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
